#!/bin/bash

BLACK='\033[0;30m'
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
WHITE='\033[0;37im'
RESET='\033[0m'

filename=$1
arg=$2
filetype="${filename##*.}"
if [ "$filetype" == "py" ]; then
    if [ "$arg" == "n" ]; then
        echo -e "$GREEN[~] Running$RESET$RED$filename$RESET$GREEN with$RESET$BLUE python3 $RESET"
        python3 $filename
    elif [ "$arg" == "i" ]; then
        echo -e "$GREEN[~] Running$RESET$RED$filename$RESET$GREEN with$RESET$BLUE python3 interactve mode $RESET"
        python3 -i $filename
    else:
        echo -e "$RED Invalid Input!$RESET"
    fi
elif [ "$filetype" == "c" ]; then
    if [ "$arg" == "n" ]; then
        echo -e "$GREEN[!] Compiling $RESET$RED$filename$RESET$GREEN with$RESET$BLUE GCC Basic Optimizations $RESET"
        gcc -o output $filename
    elif [ "$arg" == "d" ]; then
        echo -e "$GREEN[!] Compiling $RESET$RED$filename$RESET$GREEN with$RESET$BLUE GCC Debug Information $RESET"
        gcc -o output $filename -g
    elif [ "$arg" == "f" ]; then
        echo -e "$GREEN[!] Compiling $RESET$RED$filename$RESET$GREEN with$RESET$BLUE GCC Fast Optimization $RESET"
        gcc -o output $filename -O1
    fi
fi

